Carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from order.views import place_order
from mysite.settings import STATIC_ROOT
from Store.views import home,HomeView, ProductDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/',include('Store.urls')),
    path('',home,name="home"), 
    path('shop',HomeView.as_view(), name='shop'),
    path('product/<slug>/', ProductDetailView.as_view(), name='product'),
    path('cart/',include('Carts.urls')),
    path('checkout/',views.checkout, name='checkout'),
    path('place_order/',place_order, name='place_order'),
    path('user/',include('user.urls')),
    path('single_product',views.single_product, name='single_product')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
app_name = 'user'
urlpatterns = [
   path('login/',views.login1.as_view(),name='login'),
   path('register/',views.register1.as_view(),name='register'),
   path('logout/',views.logout1,name='logout'),
]

Carts/models.py
from django.contrib.auth.models import User
from django.db import models

from Store.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.cart_id)

class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return int(self.quantity * self.product.price)
    
    def __unicode__(self):
        return self.product 

Carts/views.py
from django.shortcuts import render, redirect
from Store.models import Product
from .models import  CartItem
from django.contrib.auth.decorators import login_required

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    is_exists_cart_item = CartItem.objects.filter(product=product).exists()
    if is_exists_cart_item:
                    cart_item = CartItem.objects.get(
                        product=product)
                    cart_item.quantity += 1
                    cart_item.save()
                    print(cart_item.quantity)
    else:
                cart_item = CartItem.objects.create(
                    product=product,
                    quantity=1
                )
                cart_item.save()    
    return redirect('cart')

def remove_cart(request, product_id, cart_item_id):
    product = Product.objects.get(id=product_id)
    is_exists_cart_item = CartItem.objects.filter(product=product).exists()
    if is_exists_cart_item:
                    item = CartItem.objects.get(product=product)
                    if item.quantity >= 2:
                        item.quantity -= 1
                        item.save()
                        print(item.quantity)
                    else:
                        item.delete()
    return redirect('cart')

def remove_cart_item(request, product_id, cart_item_id):
    product = Product.objects.get(id=product_id)
    item = CartItem.objects.get(
        product=product)
    item.delete()
    return redirect('cart')


@login_required(login_url='/user/login/') 
def cart(request, total=0, quantity=0):
    total = 0
    CartItems  = CartItem.objects.all()
    return render(request, 'cart.html',{'CartItems' : CartItems})
def shop(request):
    return render(request, 'shop.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Nhóm 6</title>
    
    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>
    <link type='image/x-icon' rel='icon' href="https://sheinsz.ltwebstatic.com/she_dist/images/touch-icon-ipad-72-452a7213ef.png" >
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{%static 'Css/bootstrap.min.css'%}">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{%static 'Css/font-awesome.min.css'%}">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{%static 'Css/owl.carousel.css'%}">
    <link rel="stylesheet" href="{%static 'Css/responsive.css'%}">
    <link rel="stylesheet" href="{%static 'Css/base.css'%}">
    <link rel="stylesheet" href="{%static 'Css/style.css'%}?20181209" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montagu+Slab:wght@600;700&display=swap" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% comment %} Header {% endcomment %}
    <div class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="user-menu">
                        <ul>
                            <li><a href="#"><i class="fa fa-heart"></i> Wishlist</a></li>
                            <li><a href="cart.htm"><i class="fa fa-user"></i> My Cart</a></li>
                            <li><a href="checkout.htm"><i class="fa fa-user"></i> Checkout</a></li>
                            {%if request.user.is_authenticated %}
                                <li><a href="{% url 'user:logout' %}"><i class="fa fa-user"></i> Logout</a></li>
                            {%else %}
                                <li><a href="{% url 'user:login' %}"><i class="fa fa-user"></i> Login</a></li>
                                <li><a href="{% url 'user:register' %}"><i class="fa fa-user"></i> Register</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="header-right">
                        <ul class="list-unstyled list-inline">
                            <li class="dropdown dropdown-small">
                                {%if request.user.is_authenticated %}
                                    <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key"><i class="fa fa-user" style="margin-right:5px"></i>Xin Chào: <span style="text-transform: capitalize">{{request.user.first_name}}</span> !</span></a>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End header area -->

       <div class="site-branding-area" style="">
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="logo">
                            <h1>
                                <a href="{% url 'home' %}">
                                <img src="{%static 'img/logo.png'%}" class="logo">
                                </a>
                            </h1>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div style="margin-top:44px;border-radius:5px">
                            <marquee  style="color:#5a88ca;font-size:26px;border-radius:5px;font-family: 'Montagu Slab', serif;font-weight:600">SHOP NHÓM 6</marquee>    
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- End site branding area -->
        <div class="mainmenu-area">
            <div class="container">
                <div class="row">
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            {% block active %}
                            {% endblock  %}                        
                        </ul>
                    </div>  
                </div>
            </div>
        </div> <!-- End mainmenu area -->

    {% block search %} {% endblock  %}

    {% block content %}{% endblock  %}

    {% block footer %}
                <div class="footer-top-area">
                <div class="zigzag-bottom"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                            <div class="footer-about-us">
                                <h2>u<span>Stora</span></h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>
                                <div class="footer-social">
                                    <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                                    <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                                    <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                                    <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-3 col-sm-6">
                            <div class="footer-menu">
                                <h2 class="footer-wid-title">User Navigation </h2>
                                <ul>
                                    <li><a href="#">My account</a></li>
                                    <li><a href="#">Order history</a></li>
                                    <li><a href="#">Wishlist</a></li>
                                    <li><a href="#">Vendor contact</a></li>
                                    <li><a href="#">Front page</a></li>
                                </ul>                        
                            </div>
                        </div>
                        
                        <div class="col-md-3 col-sm-6">
                            <div class="footer-menu">
                                <h2 class="footer-wid-title">Categories</h2>
                                <ul>
                                    <li><a href="#">Quần</a></li>
                                    <li><a href="#">Áo</a></li>
                                    <li><a href="#">Bộ đồ</a></li>
                                </ul>                        
                            </div>
                        </div>
                        
                        <div class="col-md-3 col-sm-6">
                            <div class="footer-newsletter">
                                <h2 class="footer-wid-title">Newsletter</h2>
                                <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>
                                <div class="newsletter-form">
                                    <form action="#">
                                        <input type="email" placeholder="Type your email">
                                        <input type="submit" value="Subscribe">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- End footer top area -->


            <div class="footer-bottom-area">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="copyright">
                                <p>&copy; © 2021 Nhóm 6          <a href="https://freshdesignweb.com" target="_blank">   group6projectpython@gmail.com</a></p>
                            </div>
                        </div>
                        
                        <div class="col-md-4">
                            <div class="footer-card-icon">
                                <i class="fa fa-cc-discover"></i>
                                <i class="fa fa-cc-mastercard"></i>
                                <i class="fa fa-cc-paypal"></i>
                                <i class="fa fa-cc-visa"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- End footer bottom area -->
    {% endblock footer %}
     

    <script src="{%static 'js/jquery.min.js'%}"></script>
    
    <!-- Bootstrap JS form CDN -->
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    
    <!-- jQuery sticky menu -->
    <script src="{%static 'js/owl.carousel.min.js'%}"></script>
    <script src="{%static 'js/jquery.sticky.js'%}"></script>
    
    <!-- jQuery easing -->
    <script src="{%static 'js/jquery.easing.1.3.min.js'%}"></script>
    
    <!-- Main Script -->
    <script src="{%static 'js/main.js'%}"></script>
    <script src="{%static 'js/activeNav.js'%}"></script>

    <!-- Slider -->
    <script type="text/javascript" src="{%static 'js/bxslider.min.js'%}"></script>
	<script type="text/javascript" src="{%static 'js/script.slider.js'%}"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-10146041-25"></script>
    <script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}
    gtag('js',new Date());gtag('config','UA-10146041-25');</script>
  </body>
</html>

templates/cart.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
     <div class="single-product-area pt-22">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                
                <div class="col-md-12">
                    <div class="product-content-right">
                        <div class="woocommerce">
                            <form method="post" action="#">
                                <table cellspacing="0" class="shop_table cart">
                                    <thead>
                                        <tr>
                                            <th class="product-remove">&nbsp;</th>
                                            <th class="product-thumbnail">Hình ảnh</th>
                                            <th class="product-name">Sản phẩm</th>
                                            <th class="product-price">Giá</th>
                                            <th class="product-quantity">Số lượng</th>
                                            <th class="product-subtotal">Tổng</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% if CartItems|length <= 0 %}
                                        <td colspan="6" style="font-size:16px;font-weight:700;padding:36px">Giỏ hàng đang trống</td>
                                    {% else %}
                                        {% for item in CartItems %}
                                            {% csrf_token %}
                                            <tr class="cart_item">
                                                <td class="product-remove" onclick="return confirm('Bạn có chắc chắn muốn xóa sản phẩm khỏi giỏ hàng?')">
                                                    <a title="Remove this item" class="remove" href="{% url 'remove_cart_item' item.product.id item.id %}">×</a> 
                                                </td>

                                                <td class="product-thumbnail">
                                                    <a href="{{product.get_absolute_url}}"><img width="145" height="145" alt="poster_1_up" class="shop_thumbnail" src="{{item.product.img.url}}" pagespeed_url_hash="2028383707" onload="pagespeed.CriticalImages.checkImageForCriticality(this);"></a>
                                                </td>

                                                <td class="product-name">
                                                    <a href="{{product.get_absolute_url}}">{{item.product.name}}</a> 
                                                </td>

                                                <td class="product-price">
                                                    <span class="amount">{{item.product.price}}</span> 
                                                </td>

                                                <td class="product-quantity">
                                                    <div class="quantity buttons_added">
                                                        <a href="{% url 'remove_cart' item.product.id item.id %}" style="font-size:12px;padding:4px 12px; border-radius:2px; background:#5a88ca;color:#fff">-</a>
                                                        <span style="padding:2px 10px;margin:0 5px; border:1px solid #5a88ca">{{item.quantity}}</span>
                                                        <a href="{% url 'add_cart' item.product.id %}" style="font-size:12px;padding:4px 12px; border-radius:2px; background:#5a88ca;color:#fff">+</a>
                                                    </div>
                                                </td>

                                                <td class="product-subtotal">
                                                    <span class="amount">${{item.sub_total}}</span> 
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    {% endif %}
                                       

                                        <tr>
                                            <td class="actions" colspan="6" >
                                                <div class="coupon">
                                                    <label for="coupon_code">Mã Giảm Giá:</label>
                                                    <input type="text" placeholder="Nhập mã tại đây" value="" id="coupon_code" class="input-text" name="coupon_code" style="margin-left:10px">
                                                    <input type="submit" value="Lấy mã giảm giá" name="apply_coupon" class="button" style="margin-left:20px">
                                                </div>
                                                {% if CartItems|length > 0 %}
                                                    <a href="{% url 'checkout' %}" style="margin-left:480px;line-height:42px;padding:11px 20px;background-color:#5a88ca;color:#fff;font-size:17px;text-decoration:none" class="checkout-button button alt wc-forward">Checkout</a>
                                                {% else %}
                                                    <a href="{% url 'shop' %}" style="margin-left:400px;line-height:42px;padding:11px 20px;background-color:#5a88ca;color:#fff;font-size:17px;text-decoration:none" class="checkout-button button alt wc-forward">Return Shop Page</a>
                                                {% endif%}
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </form>
                            </div>
                        </div>                        
                    </div>                    
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

{% block active %}
                <li class=""><a href="{% url 'home' %}">Home</a></li>
                <li class=""><a href="{% url 'shop' %}">Shop page</a></li>
                <li class="active"><a href="{% url 'cart' %}">Cart</a></li>
                
{% endblock  %}

templates/checkout.html
{% extends 'base.html' %}
{% block content %}
     <div class="single-product-area">
        <div class="zigzag-bottom"></div>
        <div class="container ">
            <div class="row">
                <div class="col-md-6 p-b-50 pt-22">
                    <div class="product-content-right">
                        <div class="woocommerce">
                           <form action="{% url 'place_order' %}" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <h3 id="order_review_heading" style="padding-left:14px">YOUR INFORMATION</h3>
                                    <div class="form-group col-sm-6">
                                        <label>First name:</label>
                                        <input type="text" name="first_name" value="First Name..." placeholder="" class="form-control">
                                    </div>
                                    <div class="form-group col-sm-6">
                                        <label>Last name:</label>
                                        <input type="text" name="last_name" value="Last name..." placeholder="" class="form-control" >
                                    </div>
                                    <div class="form-group col-sm-6">
                                        <label>Phone:</label>
                                        <input type="text" name="phone" value="+94..." class="form-control" >
                                    </div>
                                    <div class="form-group col-sm-6">
                                        <label>Email:</label>
                                        <input type="email" name="email" value="example@gmail.com" placeholder="" class="form-control" >
                                    </div>
                                    <div class="form-group col-sm-6">
                                        <label>City:</label>
                                        <input type="text" name="city" value="City..." placeholder="" class="form-control" >
                                    </div>
                                    <div class="form-group col-sm-6">
                                        <label>Address:</label>
                                        <input type="text" name="address" value="Address..." placeholder="" class="form-control" >
                                    </div>
                                </div>
			                    <button type="submit" name="submit" class="btn btn-primary " onclick="return confirm (' Bạn có muốn xác nhận đơn hàng ?')">Place Order</button>

                            </form>

                        
                        </div>                       
                    </div>                    
                </div>
            
                <div class="col-md-6 p-b-50 pt-22">
                    <div class="product-content-right">
                        <div class="woocommerce">
                            <div class="col-md-8 " style="margin-left:130px" >
                                      <h3 id="order_review_heading">Your order</h3>
                                    <div id="order_review" style="position: relative;">
                                        <table class="shop_table">
                                            <thead>
                                                <tr>
                                                    <th class="product-name">Product</th>
                                                    <th class="product-total">Total</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in CartItems %}
                                                <tr class="cart_item">
                                                    <td class="product-name">
                                                       {{item.product.name}} <strong class="product-quantity">× {{item.quantity}}</strong> </td>
                                                    <td class="product-total">
                                                        <span class="amount">${{item.sub_total}}</span> </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                            <tfoot>

                                                <tr class="shipping">
                                                    <th>Shipping and Handling</th>
                                                    <td>

                                                        Free Shipping
                                                        <input type="hidden" class="shipping_method" value="free_shipping" id="shipping_method_0" data-index="0" name="shipping_method[0]">
                                                    </td>
                                                </tr>

                                                <tr class="order-total">
                                                    <th>Order Total</th>
                                                    <td><strong><span class="amount">${{total}}</span></strong> </td>
                                                </tr>

                                            </tfoot>
                                        </table>

                                    </div>
                                </div>


                        </div>                       
                    </div>                    
                </div>
            </div>
        </div>
    </div>  
{% endblock  %}

{% block active %}
                <li class=" "><a href="{% url 'home' %}">Home</a></li>
                <li class=""><a href="{% url 'shop' %}">Shop page</a></li>
                <li class=""><a href="{% url 'cart' %}">Cart</a></li>
                <li class=""><a href="{% url 'checkout' %}">Checkout</a></li>
{% endblock  %}

templates/search.html
{% extends 'base.html' %}
{% load static %} 


{% block  content%}
    <div class="product-big-title-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product-bit-title text-center">
                        <h2>Search Result</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
     <div class="single-product-area pt-22">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row" style="text-align:center">
                {% if data|length <= 0 %}
                    <img src="{% static 'img/notfound.png' %}" style="height:130px" />
                    <h2 style="font-size:20px;padding:0;text-align:center;font-weight:700;">Không có sản phẩm phù hợp !</h2>
                    <h2 style="font-size:20px;padding:0 0 20px 0;text-align:center;font-weight:700;color:#938c8c">Hãy thử sử dụng các từ khóa chung chung hơn</h2>
                 {% else %}
                        {% for product in data %}
                            <div class="col-md-3 col-sm-6" >
                                <div class="single-shop-product">
                                    <div class="product-upper">
                                        
                                    </div>
                                    <h2><a href="{{product.get_absolute_url}}">
                                        <img src="{{product.img.url}}" alt="" style="padding-bottom:20px">
                                        {{ product.name }}
                                    </a></h2>
                                    <div class="product-carousel-price">
                                        <span class="price">${{product.price}} </span>
                                    </div>  
                                    <div class="product-option-shop">
                                        <a href="{% url 'add_cart' product.id %}" style = " border-radius:5px"class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="70" rel="nofollow" href="/canvas/shop/?add-to-cart=70">Add to cart</a>
                                    </div>                       
                                </div>
                            </div>
                        {% endfor %}
                {% endif %}
            </div>
        </div>
        
    </div>
{% endblock  %}

{% block active %}
                <li class=""><a href="{% url 'home' %}">Home</a></li>
                <li class="active "><a href="{% url 'shop' %}">Shop</a></li>
                <li class=""><a href="{% url 'cart' %}">Cart</a></li>
                <li style="margin-left: 488px; margin-top: 13px;">
                    <form action="{% url 'search' %}" class="search" method="GET" style="display: flex;">
                        <div class="input-group w-100">
                            <input style="margin-right: 11px; width: 370px; border-radius:4px" type="text" class="form-control" placeholder="Search" name="q" value="{{ q }}">
                            <div class="input-group-append" style="display: flex;">
                                <button style="padding: 7px 20px" class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </li>
{% endblock  %}